server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.112.124.237/bunnyroom
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yyc
    password: yyc
  data:
    redis:
      host: localhost
      port: 6379



mybatis:
  mapper-locations: classpath:resources/mapper/**/*.xml
  config-location: classpath:mapper/mapper-config.xml

